# Enable engine
SecRuleEngine On

# Debug & audit logs to console
SecDebugLogLevel 9
SecDebugLog /dev/stdout
SecAuditEngine On
SecAuditLog /dev/stdout

# -------- RULE 1: SQL Injection (Query String) --------
SecRule ARGS|REQUEST_URI "@rx (?i)(union|select|or[[:space:]]+1=1)" \
"id:1001,phase:2,deny,status:403,severity:CRITICAL,msg:'SQL Injection detected',log,auditlog"

# -------- RULE 2: Invalid ID --------
SecRule ARGS:id "@eq 0" \
"id:1002,phase:2,deny,status:403,severity:CRITICAL,msg:'Invalid id value',log,auditlog"

# -------- RULE 3: Password in Request Body --------
SecRequestBodyAccess On
SecRule REQUEST_BODY "@contains password" \
"id:1003,phase:2,deny,status:403,severity:CRITICAL,msg:'Sensitive data in request body',log,auditlog"
